### ISSUE TITLE
Condition card "if not empty" does not work (most of the times)

### ISSUE THREAD

**Issue by jghaanstra** [athombv/am.smarter#17]
**What is your Homey version (Settings → System)?**
Homey firmware 1.5.3 | Smarter app 3.0.1 | iKettle firmware 1.9

**What did you try to achieve?**
Turn on the iKettle2 from a flow which has a condition card as shown below.

![image](https://user-images.githubusercontent.com/4710062/32266222-cc4efcae-bee6-11e7-882b-7c36c59e247e.png)

 There is water in the kettle and the device card shows it's half full.

![image](https://user-images.githubusercontent.com/4710062/32266250-efd905e8-bee6-11e7-90db-5b8d74319282.png)

**Please include detailed steps how we can reproduce the issue**
- create a flow with the condition card as shown above
- fill up your iKettle2 with water
- try to trigger the flow

It may b necessary to test it more than once over time. What I'm seeying is that sometimes the flow does get triggered.

**Comment by RobinBol** [comment]
Thanks for reporting! I just fixed a possible cause of this issue in beta version 3.0.3. But please note, the water level of the device is rather flaky and is only reported based on estimations. Hence the water level might not accurately reflect the true water level in the device. Although, your issue is likely caused by a bug in flow condition card.

**Comment by jghaanstra** [comment]
@RobinBol Thanx, seems to be fixed with beta 3.0.3. I'm closing the issue, dont forget to push it to the app store.
